Gheb\NeatBundle\Neat\Gene:
  type: entity
  table: Gene
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    enabled:
      type: boolean
    innovation:
      type: integer
    into:
      column: fromNeuron
      type: integer
    out:
      column: toNeuron
      type: integer
    weight:
      type: decimal
      precision: 8
      scale: 2