Gheb\NeatBundle\Neat\Genome:
  type: entity
  table: Genome
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    fitness:
      type: integer
    maxNeuron:
      type: integer
    mutationRates:
      type: array
    globalRank:
      type: integer

  manyToOne:
    specie:
      targetEntity: 'Gheb\NeatBundle\Neat\Specie'
      inversedBy: genomes

  manyToMany:
    genes:
      targetEntity: 'Gheb\NeatBundle\Neat\Gene'
      cascade: ['persist']
      joinTable:
        name: Genome_genes
        joinColumns:
          genome_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          gene_id:
            referencedColumnName: id
            unique: true

    network:
      targetEntity: 'Gheb\NeatBundle\Neat\Neuron'
      cascade: ['persist']
      joinTable:
        name: Genome_neurons
        joinColumns:
          genome_id:
            referencedColumnName: id
        inverseJoinColumns:
          neuron_id:
            referencedColumnName: id
            unique: true
