Gheb\NeatBundle\Entity\Genome:
  type: entity
  table: Genome
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    fitness:
      type: integer
    maxNeuron:
      type: integer
    mutationRates:
      type: array
    globalRank:
      type: integer

  oneToMany:
    genes:
      targetEntity: 'Gheb\NeatBundle\Entity\Gene'
      cascade: ['persist', 'remove', 'refresh']
      orphanRemoval: true
      mappedBy: genome

  manyToOne:
    specie:
      targetEntity: 'Gheb\NeatBundle\Entity\Specie'
      cascade: ['persist', 'remove', 'refresh']
      orphanRemoval: true
      inversedBy: genomes
      joinColumn:
        name: specie_id
        referencedColumnName: id
        onDelete: CASCADE

  manyToMany:
    network:
      targetEntity: 'Gheb\NeatBundle\Entity\Neuron'
      cascade: ['persist', 'remove', 'refresh']
      orphanRemoval: true
      joinTable:
        name: Genome_neurons
        joinColumns:
          genome_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          neuron_id:
            referencedColumnName: id
            unique: true
            onDelete: CASCADE