Gheb\NeatBundle\Neat\Neuron:
  type: entity
  table: Neuron
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    position:
      type: integer
    value:
      type: decimal
      precision: 65
      scale: 9
    activationFunction:
      type: string

  manyToMany:
    incoming:
      targetEntity: 'Gheb\NeatBundle\Neat\Gene'
      cascade: ['persist', 'refresh']
